apiVersion: v1
kind: ConfigMap
metadata:
  name: att-config
  namespace: "ot-microservices"
data:
  api_port: "8081"
  enabled: "true"
  db_name: "attendancedb"
  host: "empms-db:3306"
  username: root
  password: password
