apiVersion: apps/v1
kind: Deployment
metadata:
  name: "empms-attendance"
  namespace: "ot-microservices"
spec:
  selector:
    matchLabels:
      app: "empms-attendance"
  replicas: 1
  template:
    metadata:
      labels:
        app: "empms-attendance"
    spec:
      containers:
      - image: sha2121/empms-attendance:1
        imagePullPolicy: Always
        name: "empms-attendance"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 200Mi   
        ports:
        - containerPort: 8081
        env:
        - name: CONFIG_FILE
          value: "/app/config.yaml"
        volumeMounts:
        - name: volume
          mountPath: /app/config.yaml  
      volumes:
      - name: volume
        hostPath:
          path: /home/opstree/project/OT-Microservices/attendance/k8s-manifests/config.yaml
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: "ot-microservices"
spec:
  selector:
    app: empms-attendance
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP